name: Python CI

on:
  push:
    branches:
      - 'developer/**'
  pull_request:
    branches:
      - 'developer/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Dummy
        run: echo Dummy Build Done

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run Python script
      run: python3 cicd/basic_check.py  # Replace 'basic_check.py' with the actual filename


  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Ensure build and test jobs complete successfully before deploying

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
